/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hourcalendar;

import java.awt.Color;
import java.util.Vector;

/**
 *
 * @author admin
 */
public class AssignaturaPane extends javax.swing.JPanel {
    Assignatura assignatura;
    private Vector<Color> colors;
    /**
     * Creates new form AssignaturaPane
     */
    public AssignaturaPane() {
        initComponents();
    }
    
    public AssignaturaPane(Assignatura assignatura) {
        initComponents();
        colors = new Vector<Color>();
        //colors pastel
        colors.add(new Color(204, 255, 204));   //verd (no pastel)
        colors.add(new Color(253, 253, 150));   //groc
        colors.add(new Color(174, 198, 207));   //blau
        colors.add(new Color(255, 105, 97));    //vermell
        colors.add(new Color(130, 105, 83));    //marro
        colors.add(new Color(255, 179, 71));    //taronja
        colors.add(new Color(177, 156, 217));   //lila
        this.assignatura = assignatura;
        sigles.setText(assignatura.getSigles());
        codi.setText(String.valueOf(assignatura.getCodi()));
        String prefixNom = "[Curs ".concat(String.valueOf(assignatura.getQuadrimestre()).concat("] "));
        nom.setText(prefixNom.concat(assignatura.getNom()));
        int idGrau = Integer.valueOf(HourCalendar.getBase().getIndexOfGrau(assignatura.getGrau()));
        Base base = HourCalendar.getBase();
        for (int i = 0; i < base.getNumGraus(); ++i) {
            Grau grauT = base.getGrauAt(i);
            if(idGrau == grauT.getID()){
                grau.setText(String.valueOf(grauT.getNom()));
                break;
            }
        }
        //grau.setText(String.valueOf(HourCalendar.getBase().getIndexOfGrau(assignatura.getGrau())));
        int colorGrau = Math.abs(HourCalendar.getBase().getIndexOfGrau(assignatura.getGrau())) % 7;
        System.out.println("COLORGRAU: ".concat(String.valueOf(colorGrau)));
        this.setBackground(colors.get(colorGrau));
        assignatura.getGrau().color = colors.get(colorGrau);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sigles = new javax.swing.JLabel();
        codi = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        nom = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        down = new javax.swing.JButton();
        up = new javax.swing.JButton();
        grau = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 10, 3, 10));

        sigles.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        sigles.setText("PROP");
        sigles.setToolTipText("");

        codi.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        codi.setText("340380");

        editar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        editar.setText("Editar");
        editar.setOpaque(false);
        editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarMouseClicked(evt);
            }
        });

        nom.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        nom.setText("PROJECTE DE PROGRAMACIÓ");

        eliminar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.setOpaque(false);
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });

        down.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        down.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hourcalendar/images/down.png"))); // NOI18N
        down.setIconTextGap(0);
        down.setMinimumSize(new java.awt.Dimension(16, 23));
        down.setOpaque(false);
        down.setPreferredSize(new java.awt.Dimension(23, 23));
        down.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downMouseClicked(evt);
            }
        });

        up.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hourcalendar/images/up.png"))); // NOI18N
        up.setIconTextGap(0);
        up.setMinimumSize(new java.awt.Dimension(16, 23));
        up.setOpaque(false);
        up.setPreferredSize(new java.awt.Dimension(23, 23));
        up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upMouseClicked(evt);
            }
        });

        grau.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grau.setText("Informàtica");
        grau.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sigles, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grau, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(down, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(sigles, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(codi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(editar)
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(eliminar)
                .addComponent(grau))
            .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(down, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormulariAssignatura(assignatura).setVisible(true);
            }
        });
    }//GEN-LAST:event_editarMouseClicked

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
        Base base = HourCalendar.getBase();
        base.removeAssignatura(assignatura);
        HourCalendar.getMainFrame().updateAssignatures();
    }//GEN-LAST:event_eliminarMouseClicked

    private void downMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downMouseClicked
        Base base = HourCalendar.getBase();
        int index = base.getIndexOfAssignatura(assignatura);
        if (index < base.getNumAssignatures() - 1) {
            Assignatura inferior = base.assignatures.set(index + 1, assignatura);
            base.assignatures.set(index, inferior);
            base.saveState();
            HourCalendar.getMainFrame().updateAssignatures();
        }
    }//GEN-LAST:event_downMouseClicked

    private void upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upMouseClicked
        Base base = HourCalendar.getBase();
        int index = base.getIndexOfAssignatura(assignatura);
        if (index > 0) {
            Assignatura superior = base.assignatures.set(index - 1, assignatura);
            base.assignatures.set(index, superior);
            base.saveState();
            HourCalendar.getMainFrame().updateAssignatures();
        }
    }//GEN-LAST:event_upMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codi;
    private javax.swing.JButton down;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel grau;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel sigles;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
