/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hourcalendar;

import javax.swing.JFrame;

/**
 *
 * @author Cristina
 */
public class FormulariAssignatura extends javax.swing.JFrame {

    /**
     * Creates new form FormulariAssignatura
     */
    public FormulariAssignatura() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        loadDefaults();
    }
    
    public FormulariAssignatura(Assignatura assignatura) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        codi.setText(String.valueOf(assignatura.getCodi()));
        codi.setEditable(false);
        sigles.setText(assignatura.getSigles());
        nom.setText(assignatura.getNom());
        horesTeoria.setText(String.valueOf(assignatura.getHoresTeoria()));
        horesPractica.setText(String.valueOf(assignatura.getHoresPractica()));
        grups.setText(String.valueOf(assignatura.getGrups()));
        
        loadDefaults();
        
        grau.setSelectedIndex(HourCalendar.getBase().getIndexOfGrau(assignatura.getGrau()));
        tipusAula.setSelectedIndex(HourCalendar.getBase().getIndexOfTipusAula(assignatura.getTipusHoresPractica()));
        tipusMateria.setSelectedIndex(HourCalendar.getBase().getIndexOfTipusMateria(assignatura.getTipus()));
        curs.setSelectedIndex(assignatura.getQuadrimestre() - 1);
    }
    
    private void loadDefaults() {
        Base base = HourCalendar.getBase();
        grau.removeAllItems();
        for (int i = 0; i < base.getNumGraus(); ++i) {
            Grau grauT = base.getGrauAt(i);
            this.grau.addItem(grauT.getCodi().concat(" - ").concat(grauT.getNom()));
        }
        tipusAula.removeAllItems();
        for (int i = 0; i < base.getNumTipusAules(); ++i) {
            TipusAula aula = base.getTipusAulaAt(i);
            this.tipusAula.addItem(aula.getNom());
        }
        tipusMateria.removeAllItems();
        for (int i = 0; i < base.getNumTipusMateries(); ++i) {
            TipusMateria materia = base.getTipusMateriaAt(i);
            this.tipusMateria.addItem(materia.getNom());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        codi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        grups = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        curs = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        horesTeoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        horesPractica = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tipusAula = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        tipusMateria = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        grau = new javax.swing.JComboBox();
        BotoAcceptar = new javax.swing.JButton();
        BotoCancelar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        sigles = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Assignatura");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setText("Nom");

        nom.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel3.setText("Codi");

        codi.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        codi.setText("0");
        codi.setToolTipText("El codi és l'identificador de l'assignatura, no es podrà editar!");
        codi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codiKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel4.setText("Nº grups pràctiques");

        grups.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        grups.setText("0");
        grups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel5.setText("Curs");

        curs.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        curs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel6.setText("H.Teoria");

        horesTeoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        horesTeoria.setText("0");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel7.setText("H.Pràctiques");

        horesPractica.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        horesPractica.setText("0");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel8.setText("Tipus H.Pràctiques");

        tipusAula.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        tipusAula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel9.setText("Tipus");

        tipusMateria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        tipusMateria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel10.setText("Grau");

        grau.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        grau.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BotoAcceptar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        BotoAcceptar.setText("Acceptar");
        BotoAcceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotoAcceptarMouseClicked(evt);
            }
        });
        BotoAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoAcceptarActionPerformed(evt);
            }
        });

        BotoCancelar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        BotoCancelar.setText("Cancel·lar");
        BotoCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotoCancelarMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel11.setText("Sigles");

        sigles.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        sigles.setToolTipText("");
        sigles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                siglesKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(83, 83, 83)
                            .addComponent(grau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(tipusAula, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BotoCancelar)
                                .addGap(61, 61, 61))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(29, 29, 29)
                                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(24, 24, 24)
                                        .addComponent(horesTeoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(horesPractica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tipusMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(1, 1, 1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(BotoAcceptar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(grups, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(codi)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sigles, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(curs, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(sigles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(codi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(curs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tipusMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(horesTeoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(horesPractica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(grups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tipusAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(grau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotoAcceptar)
                    .addComponent(BotoCancelar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void grupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grupsActionPerformed

    private void BotoAcceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotoAcceptarMouseClicked
        Base base = HourCalendar.getBase();
        TipusAula _tipusHoresPractica = base.getTipusAulaAt(tipusAula.getSelectedIndex());
        Grau _grau = base.getGrauAt(grau.getSelectedIndex());
        TipusMateria _tipusMateria = base.getTipusMateriaAt(tipusMateria.getSelectedIndex());
        int _curs = curs.getSelectedIndex() + 1;
                                                                                                                   //int _alumnes, int _quadrimestre, int _horesTeoria, int _horesPractica, TipusAula _tipusHoresPractica, int _grups) {
        base.addAssignatura(_grau, nom.getText(), sigles.getText(), Integer.parseInt(codi.getText()), _tipusMateria, 0, _curs, Integer.parseInt(horesTeoria.getText()), Integer.parseInt(horesPractica.getText()), _tipusHoresPractica, Integer.parseInt(grups.getText()));
        HourCalendar.getMainFrame().updateAssignatures();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BotoAcceptarMouseClicked

    private void BotoAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoAcceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotoAcceptarActionPerformed

    private void codiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codiKeyReleased
        //codi.setText(String.valueOf(Integer.parseInt(codi.getText())));
        String temp = codi.getText().replaceAll("\\D", "");
        if (temp.length() >= 7) {
            temp = temp.substring(0, 6);
        }
        if (!codi.getText().equals(temp)) {
            codi.setText(temp);
        }
    }//GEN-LAST:event_codiKeyReleased

    private void siglesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_siglesKeyReleased
        sigles.setText(sigles.getText().toUpperCase());
        if (sigles.getText().length() >= 6) {
            sigles.setText(sigles.getText().substring(0, 5));
        }
    }//GEN-LAST:event_siglesKeyReleased

    private void BotoCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotoCancelarMouseClicked
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BotoCancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulariAssignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulariAssignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulariAssignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulariAssignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormulariAssignatura().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotoAcceptar;
    private javax.swing.JButton BotoCancelar;
    private javax.swing.JTextField codi;
    private javax.swing.JComboBox curs;
    private javax.swing.JComboBox grau;
    private javax.swing.JTextField grups;
    private javax.swing.JTextField horesPractica;
    private javax.swing.JTextField horesTeoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField sigles;
    private javax.swing.JComboBox tipusAula;
    private javax.swing.JComboBox tipusMateria;
    // End of variables declaration//GEN-END:variables
}
