/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hourcalendar;

import hourcalendar.Base.Regles;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author admin
 */
public class FormulariOpcions extends javax.swing.JFrame {

    /**
     * Creates new form FormulariOpcions
     */
    public FormulariOpcions() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        solapar.setText(Regles.SOLAPAR_HORES_PRACTICA.getMissatge());
        solapar.setSelected(Regles.SOLAPAR_HORES_PRACTICA.get());
        assignar.setText(Regles.ASSIGNAR_HORES_RESTANTS.getMissatge());
        assignar.setSelected(Regles.ASSIGNAR_HORES_RESTANTS.get());
        prioritzar.setText(Regles.PRIORITZAR_QUADRAR_HORES.getMissatge());
        prioritzar.setSelected(Regles.PRIORITZAR_QUADRAR_HORES.get());
        textIteracions.setText(Regles.ITERACIONS_GENERADOR.getMissatge());
        iteracions.setText(String.valueOf(Regles.ITERACIONS_GENERADOR.getInt()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        solapar = new javax.swing.JCheckBox();
        assignar = new javax.swing.JCheckBox();
        prioritzar = new javax.swing.JCheckBox();
        iteracions = new javax.swing.JTextField();
        textIteracions = new javax.swing.JLabel();
        BotoAceptar = new javax.swing.JButton();
        BotoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Opcions");
        setResizable(false);

        solapar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        solapar.setText("text");
        solapar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        solapar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        solapar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                solaparPropertyChange(evt);
            }
        });

        assignar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        assignar.setText("text");
        assignar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        assignar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        prioritzar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        prioritzar.setText("text");
        prioritzar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        prioritzar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        iteracions.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        iteracions.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iteracions.setText("jTextField1");

        textIteracions.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        textIteracions.setText("jLabel1");
        textIteracions.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        BotoAceptar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        BotoAceptar.setText("Aceptar");
        BotoAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotoAceptarMouseClicked(evt);
            }
        });

        BotoCancelar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        BotoCancelar.setText("Cancel·lar");
        BotoCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotoCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prioritzar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iteracions, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textIteracions, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                    .addComponent(assignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(solapar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotoAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(solapar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(assignar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prioritzar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iteracions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIteracions, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotoAceptar)
                    .addComponent(BotoCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solaparPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_solaparPropertyChange

    }//GEN-LAST:event_solaparPropertyChange

    private void BotoAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotoAceptarMouseClicked
        // TODO add your handling code here:
        Regles.SOLAPAR_HORES_PRACTICA.set(solapar.isSelected());
        Regles.ASSIGNAR_HORES_RESTANTS.set(assignar.isSelected());
        Regles.PRIORITZAR_QUADRAR_HORES.set(prioritzar.isSelected());
        Regles.ITERACIONS_GENERADOR.set(Integer.parseInt(iteracions.getText()));
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BotoAceptarMouseClicked

    private void BotoCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotoCancelarMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BotoCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotoAceptar;
    private javax.swing.JButton BotoCancelar;
    private javax.swing.JCheckBox assignar;
    private javax.swing.JTextField iteracions;
    private javax.swing.JCheckBox prioritzar;
    private javax.swing.JCheckBox solapar;
    private javax.swing.JLabel textIteracions;
    // End of variables declaration//GEN-END:variables
}
