/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hourcalendar;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author admin
 */
public class MainFrame extends javax.swing.JFrame {
    static javax.swing.JFrame frameCalendari;
    public JPanel ContentPane;
    public ControlProgres controlProgres;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setExtendedState( getExtendedState()|JFrame.MAXIMIZED_BOTH );
        
        controlProgres = new ControlProgres(this);
        controlProgres.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        controlProgres.setVisible(false);

        ContentPane = new JPanel();
        ContentPane.setLayout(new GridBagLayout());
        ContentPane.setPreferredSize(new Dimension(Contenidor.getWidth(), Contenidor.getHeight()));
        ContentPane.setBackground(Color.YELLOW);
        JLabel label = new JLabel("");
        ContentPane.add(label);
        Contenidor.setViewportView(ContentPane);
        Contenidor.setBackground(Color.YELLOW);
        
        //Contenidor.setLayout(new GridLayout(3,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToolBar1 = new javax.swing.JToolBar();
        BotoCalendari = new javax.swing.JButton();
        BotoGenerarHorari = new javax.swing.JButton();
        BotoOpcions = new javax.swing.JButton();
        Contenidor = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HourCalendar");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jToolBar1.setRollover(true);

        BotoCalendari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hourcalendar/images/calendar2.png"))); // NOI18N
        BotoCalendari.setToolTipText("Editar el calendari de dies amb docència");
        BotoCalendari.setFocusable(false);
        BotoCalendari.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotoCalendari.setMaximumSize(new java.awt.Dimension(36, 32));
        BotoCalendari.setMinimumSize(new java.awt.Dimension(32, 32));
        BotoCalendari.setName(""); // NOI18N
        BotoCalendari.setPreferredSize(new java.awt.Dimension(32, 32));
        BotoCalendari.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotoCalendari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotoCalendariMouseClicked(evt);
            }
        });
        jToolBar1.add(BotoCalendari);

        BotoGenerarHorari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hourcalendar/images/generar.png"))); // NOI18N
        BotoGenerarHorari.setToolTipText("Generar totes les configuracions horàries pertinents segons les preferències");
        BotoGenerarHorari.setFocusable(false);
        BotoGenerarHorari.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotoGenerarHorari.setMargin(new java.awt.Insets(2, 30, 2, 30));
        BotoGenerarHorari.setMaximumSize(new java.awt.Dimension(36, 32));
        BotoGenerarHorari.setMinimumSize(new java.awt.Dimension(32, 32));
        BotoGenerarHorari.setPreferredSize(new java.awt.Dimension(32, 32));
        BotoGenerarHorari.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotoGenerarHorari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotoGenerarHorariMouseClicked(evt);
            }
        });
        jToolBar1.add(BotoGenerarHorari);

        BotoOpcions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hourcalendar/images/options.png"))); // NOI18N
        BotoOpcions.setToolTipText("Editar preferències");
        BotoOpcions.setFocusable(false);
        BotoOpcions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotoOpcions.setMaximumSize(new java.awt.Dimension(36, 32));
        BotoOpcions.setMinimumSize(new java.awt.Dimension(32, 32));
        BotoOpcions.setPreferredSize(new java.awt.Dimension(32, 32));
        BotoOpcions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotoOpcions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotoOpcionsMouseClicked(evt);
            }
        });
        jToolBar1.add(BotoOpcions);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(jToolBar1, gridBagConstraints);

        Contenidor.setBackground(new java.awt.Color(255, 153, 153));
        Contenidor.setBorder(null);
        Contenidor.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Contenidor.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        Contenidor.setMinimumSize(new java.awt.Dimension(200, 200));
        Contenidor.setPreferredSize(new java.awt.Dimension(300, 300));
        Contenidor.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ContenidorComponentResized(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(Contenidor, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotoCalendariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotoCalendariMouseClicked
        // TODO add your handling code here:
        SwingUtilities.invokeLater(new Runnable() { 
			@Override
			public void run() {
				SelectorDiesDocencia selectorDiesDocencia = new SelectorDiesDocencia();
				frameCalendari = new JFrame();
				frameCalendari.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
				Container panel = frameCalendari.getContentPane();
				panel.setLayout(new BorderLayout());
				panel.add(selectorDiesDocencia, BorderLayout.CENTER);
				frameCalendari.pack();
				frameCalendari.setSize(441, 234);    //(435,206);
                frameCalendari.setResizable(false);
				frameCalendari.setVisible(true);
			}
		});
    }//GEN-LAST:event_BotoCalendariMouseClicked

    private void BotoGenerarHorariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotoGenerarHorariMouseClicked
        // TODO add your handling code here:
        Base base = HourCalendar.getBase();
        controlProgres.setVisible(true);
        System.out.println("START UPDATE");
        base.updateDisponibilitatHoraria(2, 2013);
        System.out.println("END UPDATE");
        controlProgres.startControl();
    }//GEN-LAST:event_BotoGenerarHorariMouseClicked

    private void BotoOpcionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotoOpcionsMouseClicked

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormulariOpcions().setVisible(true);
            }
        });
    }//GEN-LAST:event_BotoOpcionsMouseClicked

    private void ContenidorComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ContenidorComponentResized
        // TODO add your handling code here:
        Base.dbgUI("CONTENIDOR COMPONENT RESIZED!".concat(String.valueOf(ContentPane.getComponentCount())).concat(String.valueOf(Contenidor.getHeight())));
        ContentPane.setPreferredSize(new Dimension(Contenidor.getWidth(), (ContentPane.getComponentCount() == 1) ? Contenidor.getHeight() : ContentPane.getHeight()));
        ContentPane.revalidate();
        ContentPane.repaint();
    }//GEN-LAST:event_ContenidorComponentResized

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        //Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotoCalendari;
    private javax.swing.JButton BotoGenerarHorari;
    private javax.swing.JButton BotoOpcions;
    public javax.swing.JScrollPane Contenidor;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
